### ISSUE TITLE
`t_symbol_kind` variant names conflict with `t_command_type`

### ISSUE THREAD

**Issue by bitquence** [vincent-lafouasse/minishell#57]
take for example:
- SIMPLE_CMD (command type) and SIMPLE_COMMAND (symbol kind)

**Comment by vincent-lafouasse** [comment]
maybe prefix the command types with `CMD_` 
`SIMPLE_CMD` -> `CMD_SIMPLE`
`PIPE_CMD`   -> `CMD_PIPELINE`

**Comment by vincent-lafouasse** [comment]
and symbols with `SYM_`
