### ISSUE TITLE
nitpick: calls to `write` may only perform a partial write

### ISSUE THREAD

**Issue by bitquence** [vincent-lafouasse/minishell#61]
as per the manual:

> The number of bytes written may be less than `count` if, for example, there is insufficient space on the underlying physical medium, or the `RLIMIT_FSIZE` resource limit is encountered (see [setrlimit(2)](https://man7.org/linux/man-pages/man2/setrlimit.2.html)), or the call was interrupted by a signal handler after having written less than `count` bytes.  (See also [pipe(7)](https://man7.org/linux/man-pages/man7/pipe.7.html).)

the only place where `write` is currently used is while writing to standard error; it may be a good idea to write a function that handles this edge case by either erroring out or retrying a fixed amount of times. #38, once merged, should also use `write` to write a here document to a temporary file, and can be handled individually

**Comment by vincent-lafouasse** [comment]
ah

**Comment by bitquence** [comment]
non-issue
