### ISSUE TITLE
piping input straight into minishell seemingly makes readline hang

### ISSUE THREAD

**Issue by bitquence** [vincent-lafouasse/minishell#63]
take for example:

`echo ls | ./minishell`

and watch the shell not respond to any control keys

**Comment by bitquence** [comment]
this is due to the fact that readline will keep polling the event hook while the `rl_event_hook` variable is non-null, even if stdin is not a tty and was closed, for some reason

either:
- don't set it in non-interactive mode
- unset it from within the event hook if it is called and stdin is closed

most likely the former since we also have to elide the prompt in non-interactive mode

**Comment by vincent-lafouasse** [comment]
I don't 100% understand, do you know how to fix it ?

**Comment by bitquence** [comment]
not very thoroughly tested but should be resolved by 4406a5f
