### ISSUE TITLE
empty string breaks path resolution

### ISSUE THREAD

**Issue by bitquence** [vincent-lafouasse/minishell#75]
`p.is_executable = access(candidate, X_OK) == 0;` apparently tests true if `candidate` is a directory

**Comment by vincent-lafouasse** [comment]
huh.

**Comment by bitquence** [comment]
currently we have:

```
minishell$ ""
minishell: /opt/homebrew/Cellar/m4/1.4.19/bin/: is a directory
```

which means it found the path above as a candidate for execution when it shouldn't have, since it's a directory and not an executable file

the only way to get the shell to `execve` a directory should be by passing it as an absolute or relative path

all this means for us is that we have to add a check in path resolution to skip over any directories

**Comment by bitquence** [comment]
a clearer example:

```
minishell$ export PATH+=:$HOME/42/minishell
minishell$ mkdir test_minishell
minishell$ test_minishell
minishell: /Users/bitquence/42/minishell/test_minishell: is a directory
```

vs with bash:

```
bash-5.2$ export PATH+=:$HOME/42/minishell
bash-5.2$ mkdir test_minishell
bash-5.2$ test_minishell
bash: test_minishell: command not found
```

in this example minishell makes it past path resolution and into the execve section while bash does not since it doesn't consider directories valid files to execute

**Comment by vincent-lafouasse** [comment]
I see, it should only be a matter of using `stat` and `S_ISDIR` then
