### ISSUE TITLE
tty settings may be broken by a background process

### ISSUE THREAD

**Issue by bitquence** [vincent-lafouasse/minishell#86]
run `vim` in minishell and `kill -KILL $VIM_PID_HERE` in another terminal and notice how the terminal's output breaks

we are meant to save the tty attributes at initialization and set them again if a process terminates due to a signal

**Comment by bitquence** [comment]
186ce61 makes it so that we save the tty properties using `tcgetattr` inside of `t_state`

**Comment by anevski-stefan** [comment]
test
